name: PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate-pr:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install minimal dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy pandas pytest
        
    - name: Quick validation
      run: |
        echo "Running FABADA validation tests..."
        python tests/test_smoke.py
        pytest tests/test_spectrum.py::TestSpectrumDenoising::test_fabada_spectrum_basic -v --tb=line
        echo "✅ PR validation completed successfully!"