name: Quick Tests

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]

jobs:
  quick-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install numpy scipy pandas pytest
        
    - name: Run smoke tests
      run: |
        python tests/test_smoke.py
        
    - name: Run core spectrum tests
      run: |
        pytest tests/test_spectrum.py::TestSpectrumDenoising::test_fabada_spectrum_basic -v
        pytest tests/test_spectrum.py::TestSpectrumDenoising::test_fabada_improves_psnr -v
        
    - name: Run integration workflow test
      run: |
        pytest tests/test_integration.py::TestFabadaIntegration::test_spectrum_example_workflow -v